myblog/models/post.py
from datetime import datetime
from myblog import db

class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    title = db.Column(db.String(100))
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, author, title, body) -> None:
        self.author = author
        self.title = title
        self.body = body
    
    def __repr__(self) -> str:
        return f"User: {self.title}"

myblog/models/user.py
from myblog import db

class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.Text)

    def __init__(self, username, password) -> None:
        self.username = username
        self.password = password
    
    def __repr__(self) -> str:
        return f"User: {self.username}"

myblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Cargar las configuraciones
app.config.from_object('config.DevelopmentConfig')
db = SQLAlchemy(app)

# Importar vistas
from myblog.views.auth import auth
app.register_blueprint(auth)

from myblog.views.blog import blog
app.register_blueprint(blog)

with app.app_context():
    db.create_all()

myblog/views/auth.py
import functools
from flask import render_template, Blueprint, flash, g, redirect, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from myblog.models.user import User
from myblog import db

auth = Blueprint("auth", __name__, url_prefix="/auth")

# registrar un usuario
@auth.route("/register", methods=["GET","POST"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        user = User(username, generate_password_hash(password))

        error = None
        if not username:
            error = "Se requiere nombre de usuario"
        elif not password:
            error = "Se requiere una contraseña"
        
        user_name = User.query.filter_by(username=username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            error = f"El usuario {username} ya esta registrado"
        flash(error)
        
    return render_template("auth/register.html")


# Iniciar sesion
@auth.route("/login", methods=["GET","POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        
        error = None
        
        user = User.query.filter_by(username=username).first()

        if user == None:
            error = "Nombre de usuario incorrecto"
        elif not check_password_hash(user.password, password):
            error = "Contraseña incorrecta"

        if error is None:
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("blog.index"))

        flash(error)
        
    return render_template("auth/login.html")


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get_or_404(user_id)


@auth.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("blog.index"))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))            
        return view(**kwargs)
    return wrapped_view

myblog/views/blog.py
from flask import render_template, flash, g, Blueprint, redirect, request, url_for
from werkzeug.exceptions import abort
from myblog.models.post import Post
from myblog.models.user import User
from myblog.views.auth import login_required
from myblog import db

blog = Blueprint("blog", __name__)

# Obtener un usuario
def get_user(id):
    user = User.query.get_or_404(id)
    return user

@blog.route("/")
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    db.session.commit()
    return render_template("blog/index.html", posts=posts, get_user=get_user)


# registrar un post
@blog.route("/blog/create", methods=["GET","POST"])
@login_required
def create():
    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = "Se requiere un titulo"
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for("blog.index"))

        flash(error)
        
    return render_template("blog/create.html")



def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe')
    if check_author and post.author != g.user.id:
        abort(404)

    return post

# update post
@blog.route("/blog/update/<int:id>", methods=["GET","POST"])
@login_required
def update(id):

    post = get_post(id)

    if request.method == "POST":
        post.title = request.form["title"]
        post.body = request.form["body"]

        error = None
        if not post.title:
            error = "Se requiere un titulo"
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for("blog.index"))

        flash(error)
        
    return render_template("blog/update.html", post=post)


# Eliminar un post
@blog.route("/blog/delete/<int:id>")
@login_required
def delete(id):
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.index'))

myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico') }}" type="image/x-icon">
    <title>{% block title %}{% endblock %}My-Blog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header class="header">
        <div class="nav">
            <div>
                <a href="{{ url_for('blog.index') }}">
                    <h1>My Blog</h1>
                </a>
            </div>
            <nav>
                {% if g.user %}
                <img src="{{ url_for('static', filename='img/user.png') }}" alt="">
                <span>{{ g.user.username }}</span>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                {% else %}
                <a href="{{ url_for('auth.register') }}">Registrar usuario</a>
                <a href="{{ url_for('auth.login') }}">Iniciar Sesión</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <section>
        <div class="content">
            <header>{% block header %}{% endblock %}</header>

            {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}
            
            {% block content %}{% endblock %}
        </div>        
    </section>
</body>
</html>

myblog/templates/blog/create.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Crear una publicación{% endblock %}</h2>
{% endblock %}

{% block content %}
<form action="/blog/create" method="POST">
    <label for="title">Título</label>
    <input type="text" name="title" id="title" required>
    <label for="contenido">Contenido</label>
    <textarea name="body" id="body" cols="30" rows="10"></textarea>
    <input type="submit" value="Guardar">
</form>
{% endblock %}

myblog/templates/blog/index.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Publicaciones{% endblock %}</h2>
    {% if g.user %}
        <a href="{{ url_for('blog.create') }}">Nueva publicación</a>
    {% endif %}
{% endblock %}

{% block content %}
{% for post in posts %}
    <article>
        <header>
            <div>
                <h1>{{ post.title }}</h1>
                <div class="about">
                    Publicado por {{ get_user(post.author).username }}
                    el {{ post.created.strftime('%Y-%m-%d') }}
                </div>    
            </div>

            <div>
                {% if g.user.id == post.author%}
                    <a href="{{ url_for('blog.update', id=post.id) }}">Editar</a>
                    <a href="{{ url_for('blog.delete', id=post.id) }}">Eliminar</a>
                {% endif %}
            </div>
        </header>
        <div>
            <p>{{ post.body }}</p>
        </div>
    </article>
{% endfor %}
{% endblock %}

myblog/templates/blog/update.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Actualizar una publicación{% endblock %}</h2>
{% endblock %}

{% block content %}
<form method="POST">
    <label for="title">Título</label>
    <input type="text" name="title" id="title" required value="{{ post.title }}">
    <label for="contenido">Contenido</label>
    <textarea name="body" id="body" cols="30" rows="10">{{ post.body }}</textarea>
    <input type="submit" value="Guardar">
</form>
{% endblock %}